# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: windows-2019

steps:
- task: Maven@3
  displayName: Maven Smoke
  inputs:
    mavenPomFile: pom.xml
    goals: test -P$(testsuite) -Dbrowser=$(browser) -Dremote=no
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)'
    Contents: '**/reports/*'
    TargetFolder: '$(build.artifactstagingdirectory)'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'ExtentReports'
    publishLocation: 'Container'

